name: release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/zjg/-mail-protocol
            git reset --hard origin/master
            git clean -f
            git checkout master
            git pull origin master
            if [ $(docker ps -aq --filter name=mail_protocol) ]; then docker rm -f mail_protocol; docker rmi mail_protocol; fi
            docker build -t 'mail_protocol' .
            docker run -d -p 8025:8025 -p 8026:8026 --mount type=bind,source=/home/zjg/-mail-protocol/mail,target=/app/mail --name=mail_protocol mail_protocol